// src/components/socials.tsx
import React from 'react';
import styled from 'styled-components';

const Wrapper = styled.ul`
    position: absolute;
    top: 50%;
    right: 50px;
    transform: translateY(-50%);
    float: right;
    writing-mode: vertical-lr;
`;

const Item = styled.li`
    float: left;
    margin-bottom: 40px;

    :last-child {
        margin: 0;
    }

    & > a {
        font-family: 'SF Display';
        font-size: 14px;
        letter-spacing: 3px;
        font-weight: 700;
    }
`;

const items = [
    {
        name: 'github',
        url: 'https://github.com/zlindner'
    },
    {
        name: 'linkedin',
        url: 'https://linkedin.com/in/zachlindner'
    },
    {
        name: 'resume',
        url: `${process.env.PUBLIC_URL}/Resume.pdf`
    }
];

const Socials = () => {
    return (
        <Wrapper>
            {items.map(item => (
                <Item key={`socials_${item.name}`}>
                    <a href={item.url} target='_blank' rel='noopener noreferrer'>
                        {item.name.toUpperCase()}
                    </a>
                </Item>
            ))}
        </Wrapper>
    );
};

export default Socials;

// src/components/socials.vue
<template>
    <div class="socials">
        <ul>
            <li><a href="https://github.com/zlindner" target="_blank noopener noreferrer">github</a></li>
            <li><a href="https://linkedin.com/in/zachlindner" target="_blank noopener noreferrer">linkedin</a></li>
            <li><a href="Resume.pdf" target="_blank noopener noreferrer">resume</a></li>
        </ul>
    </div>
</template>

<script>
    export default {
        name: 'Socials'
    };
</script>

<style lang="sass" scoped>
    .socials
        position: absolute
        top: 40px
        right: 40px

        ul
            list-style-type: none

            li
                display: inline-block
                margin-left: 40px

                a
                    font-size: 18px
</style>
